server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  output:
    ans1:
      enabled: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/db
    username: root
    password:
